// <auto-generated />
namespace TestTaskWebitel.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateRelationshipBetweenTablesProductAndOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateRelationshipBetweenTablesProductAndOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202102191415475_CreateRelationshipBetweenTablesProductAndOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
